import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    title: "Jeevan Roshini",
    subtitle: "Community Health Programme",
    offlineMode: "Offline Mode",
    online: "Online",
    offline: "Offline",
    syncPending: "Sync Pending",
    syncSuccess: "Data synchronized with central server successfully!",
    vhwRole: "Village Health Worker",
    directorRole: "Project Director",
    adminRole: "Super Admin (Ayathana Trust)",
    dashboard: "Dashboard",
    villageReg: "Village Registration",
    familyReg: "Family Registration",
    individualReg: "Individual Health Registry",
    echr: "Electronic Community Health Records",
    fieldVisits: "Field Visit Tracker",
    communityProg: "Community Programs",
    hrAttendance: "Attendance & HR",
    vulnerableRegistry: "Vulnerable Registry",
    trainingCenter: "Training & Development",
    reports: "Reports & Documents",
    riskAlerts: "Risk Alerts",
    save: "Save Record",
    saving: "Saving...",
    offlineQueue: "Saved locally (Offline)",
    syncNow: "Sync Now",
    name: "Name",
    age: "Age",
    gender: "Gender",
    phone: "Mobile Number",
    village: "Village",
    selectVillage: "Select Village",
    houseNo: "House Number",
    economicStatus: "Economic Status",
    waterSource: "Drinking Water Source",
    toiletStatus: "Toilet Availability",
    chronicDiseases: "Chronic Diseases",
    bloodGroup: "Blood Group",
    pregnancyStatus: "Pregnancy Status",
    vaccinationStatus: "Vaccination Status",
    disabilityStatus: "Disability Status",
    alertsCount: "High-Risk Alerts",
    maternalStatus: "Maternal Health Status",
    attendanceCheckIn: "GPS Attendance Check-In",
    checkedIn: "Checked In",
    checkIn: "Check In",
    checkOut: "Check Out",
    gpsMock: "Simulated GPS Coordinates",
    signInToPortal: "Sign in to Portal",
    enterCredentials: "Enter your credentials to access health metrics",
    emailAddress: "Email Address",
    passwordLabel: "Password",
    keepMeSignedIn: "Keep me signed in",
    forgotPassword: "Forgot password?",
    accessPortal: "Access Portal",
    signingIn: "Signing in...",
    quickDemoAccess: "Quick Demo Access",
    liveClinicalMetrics: "Live Clinical Network Metrics",
    needHelp: "Need help?",
    contactAdmin: "Contact admin",
    privacyPolicy: "Privacy Policy",
    hello: "HELLO !",
    pleaseEnterDetails: "Please enter your details to continue"
  },
  kn: {
    title: "ಜೀವನ ರೋಶಿನಿ",
    subtitle: "ಸಮುದಾಯ ಆರೋಗ್ಯ ಕಾರ್ಯಕ್ರಮ",
    offlineMode: "ಆಫ್‌ಲೈನ್ ಮೋಡ್",
    online: "ಆನ್‌ಲೈನ್",
    offline: "ಆಫ್‌ಲೈನ್",
    syncPending: "ಸಿಂಕ್ ಬಾಕಿ ಇದೆ",
    syncSuccess: "ಕೇಂದ್ರ ಸರ್ವರ್‌ನೊಂದಿಗೆ ಡೇಟಾವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಿಂಕ್ ಮಾಡಲಾಗಿದೆ!",
    vhwRole: "ಗ್ರಾಮ ಆರೋಗ್ಯ ಕಾರ್ಯಕರ್ತರು (VHW)",
    directorRole: "ಯೋಜನಾ ನಿರ್ದೇಶಕರು",
    adminRole: "ಸೂಪರ್ ಅಡ್ಮಿನ್ (ಆಯತನ ಟ್ರಸ್ಟ್)",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    villageReg: "ಗ್ರಾಮ ನೋಂದಣಿ",
    familyReg: "ಕುಟುಂಬ ನೋಂದಣಿ",
    individualReg: "ವೈಯಕ್ತಿಕ ಆರೋಗ್ಯ ದಾಖಲೆ",
    echr: "ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಸಮುದಾಯ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು",
    fieldVisits: "ಕ್ಷೇತ್ರ ಭೇಟಿ ಟ್ರ್ಯಾಕರ್",
    communityProg: "ಸಮುದಾಯ ಕಾರ್ಯಕ್ರಮಗಳು",
    hrAttendance: "ಹಾಜರಾತಿ ಮತ್ತು ಮಾನವ ಸಂಪನ್ಮೂಲ",
    vulnerableRegistry: "ದುರ್ಬಲ ವರ್ಗಗಳ ದಾಖಲಾತಿ",
    trainingCenter: "ತರಬೇತಿ ಮತ್ತು ಅಭಿವೃದ್ಧಿ",
    reports: "ವರದಿಗಳು ಮತ್ತು ದಾಖಲೆಗಳು",
    riskAlerts: "ಅಪಾಯದ ಎಚ್ಚರಿಕೆಗಳು",
    save: "ದಾಖಲೆಯನ್ನು ಉಳಿಸಿ",
    saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    offlineQueue: "ಸ್ಥಳೀಯವಾಗಿ ಉಳಿಸಲಾಗಿದೆ (ಆಫ್‌ಲೈನ್)",
    syncNow: "ಈಗ ಸಿಂಕ್ ಮಾಡಿ",
    name: "ಹೆಸರು",
    age: "ವಯಸ್ಸು",
    gender: "ಲಿಂಗ",
    phone: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    village: "ಗ್ರಾಮ",
    selectVillage: "ಗ್ರಾಮವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    houseNo: "ಮನೆ ಸಂಖ್ಯೆ",
    economicStatus: "ಆರ್ಥಿಕ ಸ್ಥಿತಿ",
    waterSource: "ಕುಡಿಯುವ ನೀರಿನ ಮೂಲ",
    toiletStatus: "ಶೌಚಾಲಯದ ಲಭ್ಯತೆ",
    chronicDiseases: "ದೀರ್ಘಕಾಲದ ಕಾಯಿಲೆಗಳು",
    bloodGroup: "ರಕ್ತದ ಗುಂಪು",
    pregnancyStatus: "ಗರ್ಭಧಾರಣೆಯ ಸ್ಥಿತಿ",
    vaccinationStatus: "ಲಸಿಕೆ ಸ್ಥಿತಿ",
    disabilityStatus: "ಅಂಗವೈಕಲ್ಯ ಸ್ಥಿತಿ",
    alertsCount: "ಹೆಚ್ಚಿನ ಅಪಾಯದ ಎಚ್ಚರಿಕೆಗಳು",
    maternalStatus: "ತಾಯಂದಿರ ಆರೋಗ್ಯ ಸ್ಥಿತಿ",
    attendanceCheckIn: "GPS ಹಾಜರಾತಿ ಚೆಕ್-ಇನ್",
    checkedIn: "ಹಾಜರಾತಿ ದಾಖಲಾಗಿದೆ",
    checkIn: "ಚೆಕ್-ಇನ್",
    checkOut: "ಚೆಕ್-ಔಟ್",
    gpsMock: "ಸಿಮ್ಯುಲೇಟೆಡ್ ಜಿಪಿಎಸ್ ನಿರ್ದೇಶಾಂಕಗಳು",
    signInToPortal: "ಪೋರ್ಟಲ್‌ಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ",
    enterCredentials: "ಆರೋಗ್ಯ ಮೆಟ್ರಿಕ್‌ಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ನಿಮ್ಮ ರುಜುವಾತುಗಳನ್ನು ನಮೂದಿಸಿ",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    passwordLabel: "ಪಾಸ್‌ವರ್ಡ್",
    keepMeSignedIn: "ನನ್ನನ್ನು ಸೈನ್ ಇನ್ ಆಗಿ ಇರಿಸಿ",
    forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    accessPortal: "ಪೋರ್ಟಲ್ ಪ್ರವೇಶಿಸಿ",
    signingIn: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...",
    quickDemoAccess: "ತ್ವರಿತ ಡೆಮೊ ಪ್ರವೇಶ",
    liveClinicalMetrics: "ಲೈವ್ ಕ್ಲಿನಿಕಲ್ ನೆಟ್‌ವರ್ಕ್ ಮೆಟ್ರಿಕ್ಸ್",
    needHelp: "ಸಹಾಯ ಬೇಕೇ?",
    contactAdmin: "ನಿರ್ವಾಹಕರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    privacyPolicy: "ಗೌಪ್ಯತಾ ನೀತಿ",
    hello: "ನಮಸ್ಕಾರ !",
    pleaseEnterDetails: "ಮುಂದುವರಿಯಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ"
  },
  ml: {
    title: "ജീവൻ റോഷ്നി",
    subtitle: "കമ്മ്യൂണിറ്റി ഹെൽത്ത് പ്രോഗ്രാം",
    offlineMode: "ഓഫ്‌ലൈൻ മോഡ്",
    online: "ഓൺലൈൻ",
    offline: "ഓഫ്‌ലൈൻ",
    syncPending: "സമന്വയം തീർപ്പാക്കാനുണ്ട്",
    syncSuccess: "ഡാറ്റ വിജയകരമായി സെൻട്രൽ സെർവറിലേക്ക് സമന്വയിപ്പിച്ചു!",
    vhwRole: "വില്ലേജ് ഹെൽത്ത് വർക്കർ",
    directorRole: "പ്രോജക്ട് ഡയറക്ടർ",
    adminRole: "സൂപ്പർ അഡ്മിൻ (ആയതന ട്രസ്റ്റ്)",
    dashboard: "ഡാഷ്ബോർഡ്",
    villageReg: "വില്ലേജ് രജിസ്ട്രേഷൻ",
    familyReg: "കുടുംബ രജിസ്ട്രേഷൻ",
    individualReg: "വ്യക്തിഗത ആരോഗ്യ രജിസ്ട്രി",
    echr: "ഇലക്ട്രോണിക് ഹെൽത്ത് റെക്കോർഡുകൾ",
    fieldVisits: "ഫീൽഡ് സന്ദർശന ട്രാക്കർ",
    communityProg: "കമ്മ്യൂണിറ്റി പ്രോഗ്രാമുകൾ",
    hrAttendance: "ഹാജരും ജീവനക്കാരും",
    vulnerableRegistry: "ദുർബല വിഭാഗ രജിസ്ട്രി",
    trainingCenter: "പരിശീലനവും വികസനവും",
    reports: "റിപ്പോർട്ടുകളും രേഖകളും",
    riskAlerts: "അപകട മുന്നറിയിപ്പുകൾ",
    save: "രേഖപ്പെടുത്തുക",
    saving: "സൂക്ഷിക്കുന്നു...",
    offlineQueue: "പ്രാദേശികമായി സംരക്ഷിച്ചു (ഓഫ്‌ലൈൻ)",
    syncNow: "ഇപ്പോൾ സമന്വയിപ്പിക്കുക",
    name: "പേര്",
    age: "പ്രായം",
    gender: "ലിംഗഭേദം",
    phone: "മൊബൈൽ നമ്പർ",
    village: "ഗ്രാമം",
    selectVillage: "ഗ്രാമം തിരഞ്ഞെടുക്കുക",
    houseNo: "വീട്ടു നമ്പർ",
    economicStatus: "സാമ്പത്തിക സ്ഥിതി",
    waterSource: "കുടിവെള്ള സ്രോതസ്സ്",
    toiletStatus: "ശുചിമുറി ലഭ്യത",
    chronicDiseases: "സ്ഥിരമായ രോഗങ്ങൾ",
    bloodGroup: "രക്തഗ്രൂപ്പ്",
    pregnancyStatus: "ഗർഭാവസ്ഥ",
    vaccinationStatus: "പ്രതിരോധ കുത്തിവയ്പ്പ് നില",
    disabilityStatus: "വൈകല്യ നില",
    alertsCount: "ഉയർന്ന അപകടസാധ്യതകൾ",
    maternalStatus: "മാതൃ ആരോഗ്യ നില",
    attendanceCheckIn: "ജിപിഎസ് ഹാജർ ചെക്ക്-ഇൻ",
    checkedIn: "ഹാജർ രേഖപ്പെടുത്തി",
    checkIn: "ചെക്ക് ഇൻ",
    checkOut: "ചെക്ക് ഔട്ട്",
    gpsMock: "ജിപിഎസ് ലൊക്കേഷൻ",
    signInToPortal: "പോർട്ടലിലേക്ക് സൈൻ ഇൻ ചെയ്യുക",
    enterCredentials: "ആരോഗ്യ വിവരങ്ങൾ കാണുന്നതിനായി നിങ്ങളുടെ വിവരങ്ങൾ നൽകുക",
    emailAddress: "ഇമെയിൽ വിലാസം",
    passwordLabel: "പാസ്‌വേഡ്",
    keepMeSignedIn: "എന്നെ സൈൻ ഇൻ ആയി നിലനിർത്തുക",
    forgotPassword: "പാസ്‌വേഡ് മറന്നുപോയോ?",
    accessPortal: "പോർട്ടൽ പ്രവേശിക്കുക",
    signingIn: "സൈൻ ഇൻ ചെയ്യുന്നു...",
    quickDemoAccess: "ഡെമോ പ്രവേശനം",
    liveClinicalMetrics: "തത്സമയ ക്ലിനിക്കൽ നെറ്റ്‌വർക്ക് വിവരങ്ങൾ",
    needHelp: "സഹായം ആവശ്യമുണ്ടോ?",
    contactAdmin: "അഡ്മിനെ ബന്ധപ്പെടുക",
    privacyPolicy: "സ്വകാര്യതാ നയം",
    hello: "ഹലോ !",
    pleaseEnterDetails: "തുടരുന്നതിന് ദയവായി നിങ്ങളുടെ വിവരങ്ങൾ നൽകുക"
  },
  hi: {
    title: "जीवन रोशनी",
    subtitle: "सामुदायिक स्वास्थ्य कार्यक्रम",
    offlineMode: "ऑफलाइन मोड",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    syncPending: "सिंक लंबित है",
    syncSuccess: "डेटा केंद्रीय सर्वर के साथ सफलतापूर्वक सिंक हो गया है!",
    vhwRole: "ग्राम स्वास्थ्य कार्यकर्ता (VHW)",
    directorRole: "परियोजना निदेशक",
    adminRole: "सुपर एडमिन (आयतन ट्रस्ट)",
    dashboard: "डैशबोर्ड",
    villageReg: "ग्राम पंजीकरण",
    familyReg: "परिवार पंजीकरण",
    individualReg: "व्यक्तिगत स्वास्थ्य रजिस्ट्री",
    echr: "इलेक्ट्रॉनिक स्वास्थ्य रिकॉर्ड",
    fieldVisits: "क्षेत्र दौरा ट्रैकर",
    communityProg: "सामुदायिक कार्यक्रम",
    hrAttendance: "उपस्थिति और एचआर",
    vulnerableRegistry: "कमजोर वर्ग रजिस्ट्री",
    trainingCenter: "प्रशिक्षण एवं विकास",
    reports: "रिपोर्ट और दस्तावेज",
    riskAlerts: "जोखिम अलर्ट",
    save: "सुरक्षित करें",
    saving: "सुरक्षित हो रहा है...",
    offlineQueue: "स्थानीय रूप से सहेजा गया (ऑफलाइन)",
    syncNow: "अभी सिंक करें",
    name: "नाम",
    age: "उम्र",
    gender: "लिंग",
    phone: "मोबाइल नंबर",
    village: "ग्राम",
    selectVillage: "ग्राम चुनें",
    houseNo: "मकान नंबर",
    economicStatus: "आर्थिक स्थिति",
    waterSource: "पेयजल स्रोत",
    toiletStatus: "शौचालय की उपलब्धता",
    chronicDiseases: "पुरानी बीमारियाँ",
    bloodGroup: "रक्त समूह",
    pregnancyStatus: "गर्भावस्था की स्थिति",
    vaccinationStatus: "टीकाकरण की स्थिति",
    disabilityStatus: "विकलांगता की स्थिति",
    alertsCount: "उच्च जोखिम अलर्ट",
    maternalStatus: "मातृ स्वास्थ्य स्थिति",
    attendanceCheckIn: "जीपीएस उपस्थिति चेक-इन",
    checkedIn: "उपस्थिति दर्ज की गई",
    checkIn: "चेक-इन",
    checkOut: "चेक-आउट",
    gpsMock: "सिम्युलेटेड जीपीएस निर्देशांक",
    signInToPortal: "पोर्टल में साइन इन करें",
    enterCredentials: "स्वास्थ्य मेट्रिक्स तक पहुँचने के लिए अपने क्रेडेंशियल दर्ज करें",
    emailAddress: "ईमेल पता",
    passwordLabel: "पासवर्ड",
    keepMeSignedIn: "मुझे साइन इन रखें",
    forgotPassword: "पासवर्ड भूल गए?",
    accessPortal: "पोर्टल तक पहुँचें",
    signingIn: "साइन इन हो रहा है...",
    quickDemoAccess: "त्वरित डेमो एक्सेस",
    liveClinicalMetrics: "लाइव क्लिनिकल नेटवर्क मेट्रिक्स",
    needHelp: "मदद चाहिए?",
    contactAdmin: "व्यवस्थापक से संपर्क करें",
    privacyPolicy: "गोपनीयता नीति",
    hello: "नमस्ते !",
    pleaseEnterDetails: "जारी रखने के लिए कृपया अपना विवरण दर्ज करें"
  },
  te: {
    title: "జీవన్ రోషిణి",
    subtitle: "కమ్యూనిటీ హెల్త్ ప్రోగ్రామ్",
    offlineMode: "ఆఫ్‌లైన్ మోడ్",
    online: "ఆన్‌లైన్",
    offline: "ఆఫ్‌లైన్",
    syncPending: "సింక్ పెండింగ్‌లో ఉంది",
    syncSuccess: "డేటా విజయవంతంగా సెంట్రల్ సర్వర్‌తో సింక్ చేయబడింది!",
    vhwRole: "గ్రామ ఆరోగ్య కార్యకర్త",
    directorRole: "ప్రాజెక్ట్ డైరెక్టర్",
    adminRole: "సూపర్ అడ్మిన్ (ఆయతన ట్రస్ట్)",
    dashboard: "డ్యాష్‌బోర్డ్",
    villageReg: "గ్రామ నమోదు",
    familyReg: "కుటుంబ నమోదు",
    individualReg: "వ్యక్తిగత ఆరోగ్య రిజిస్ట్రీ",
    echr: "ఎలక్ట్రానిక్ హెల్త్ రికార్డులు",
    fieldVisits: "ఫీల్డ్ విజిట్ ట్రాకర్",
    communityProg: "కమ్యూనిటీ ప్రోగ్రామ్‌లు",
    hrAttendance: "హాజరు మరియు హెచ్‌ఆర్",
    vulnerableRegistry: "వల్నరబుల్ రిజిస్ట్రీ",
    trainingCenter: "శిక్షణ మరియు అభివృద్ధి",
    reports: "నివేదికలు మరియు పత్రాలు",
    riskAlerts: "రిస్క్ అలర్ట్స్",
    save: "రికార్డును సేవ్ చేయి",
    saving: "సేవ్ అవుతోంది...",
    offlineQueue: "స్థానికంగా సేవ్ చేయబడింది (ఆఫ్‌లైన్)",
    syncNow: "ఇప్పుడే సింక్ చేయి",
    name: "పేరు",
    age: "వయస్సు",
    gender: "లింగం",
    phone: "మొబైల్ నంబర్",
    village: "గ్రామం",
    selectVillage: "గ్రామాన్ని ఎంచుకోండి",
    houseNo: "ఇంటి నంబర్",
    economicStatus: "ఆర్థిక స్థితి",
    waterSource: "త్రాగునీటి వనరు",
    toiletStatus: "శౌచాలయం లభ్యత",
    chronicDiseases: "దీర్ఘకాలిక వ్యాధులు",
    bloodGroup: "రక్త గ్రూపు",
    pregnancyStatus: "గర్భధారణ స్థితి",
    vaccinationStatus: "టీకా స్థితి",
    disabilityStatus: "వైకల్య స్థితి",
    alertsCount: "అధిక రిస్క్ అలర్ట్స్",
    maternalStatus: "మాతృ ఆరోగ్య స్థితి",
    attendanceCheckIn: "GPS హాజరు చెక్-ఇన్",
    checkedIn: "హాజరు నమోదైంది",
    checkIn: "చెక్-ఇన్",
    checkOut: "చెక్-అవుట్",
    gpsMock: "సిమ్యులేటెడ్ GPS కోఆర్డినేట్స్",
    signInToPortal: "పోర్టల్‌లోకి సైన్ ఇన్ చేయండి",
    enterCredentials: "ఆరోగ్య కొలమానాలను యాక్సెస్ చేయడానికి మీ ఆధారాలను నమోదు చేయండి",
    emailAddress: "ఈమెయిల్ చిరునామా",
    passwordLabel: "పాసవర్డ్",
    keepMeSignedIn: "నన్ను సైన్ ఇన్ చేసి ఉంచండి",
    forgotPassword: "పాసవర్డ్ మర్చిపోయారా?",
    accessPortal: "పోర్టల్ యాక్సెస్ చేయండి",
    signingIn: "సైన్ ఇన్ అవుతోంది...",
    quickDemoAccess: "త్వరిత డెమో యాక్సెస్",
    liveClinicalMetrics: "లైవ్ క్లినికల్ నెట్‌వర్క్ కొలమానాలు",
    needHelp: "సహాయం కావాలా?",
    contactAdmin: "అడ్మిన్‌ను సంప్రదించండి",
    privacyPolicy: "గోప్యతా విధానం",
    hello: "నమస్కారం !",
    pleaseEnterDetails: "కొనసాగడానికి దయచేసి మీ వివరాలను నమోదు చేయండి"
  },
  ta: {
    title: "ஜீவன் ரோஷினி",
    subtitle: "சமூக சுகாதார திட்டம்",
    offlineMode: "ஆஃப்லைன் பயன்முறை",
    online: "ஆன்லைன்",
    offline: "ஆஃப்லைன்",
    syncPending: "ஒத்திசைவு நிலுவையில் உள்ளது",
    syncSuccess: "தரவு மத்திய சேவையகத்துடன் வெற்றிகரமாக ஒத்திசைக்கப்பட்டது!",
    vhwRole: "கிராம சுகாதார ஊழியர்",
    directorRole: "திட்ட இயக்குனர்",
    adminRole: "சூப்பர் அட்மின் (ஆயதன அறக்கட்டளை)",
    dashboard: "டாஷ்போர்டு",
    villageReg: "கிராம பதிவு",
    familyReg: "குடும்ப பதிவு",
    individualReg: "தனிநபர் சுகாதார பதிவேடு",
    echr: "மின்னணு சமூக சுகாதார பதிவுகள்",
    fieldVisits: "கள வருகை கண்காணிப்பாளர்",
    communityProg: "சமூக திட்டங்கள்",
    hrAttendance: "வருகை மற்றும் மனிதவள",
    vulnerableRegistry: "பாதிக்கப்படக்கூடிய பதிவேடு",
    trainingCenter: "பயிற்சி மற்றும் மேம்பாடு",
    reports: "அறிக்கைகள் மற்றும் ஆவணங்கள்",
    riskAlerts: "அபாய எச்சரிக்கைகள்",
    save: "பதிவை சேமி",
    saving: "சேமிக்கப்படுகிறது...",
    offlineQueue: "உள்ளூரில் சேமிக்கப்பட்டது (ஆஃப்லைன்)",
    syncNow: "இப்போது ஒத்திசை",
    name: "பெயர்",
    age: "வயது",
    gender: "பாலினம்",
    phone: "கைபேசி எண்",
    village: "கிராமம்",
    selectVillage: "கிராமத்தைத் தேர்ந்தெடுக்கவும்",
    houseNo: "வீட்டு எண்",
    economicStatus: "பொருளாதார நிலை",
    waterSource: "குடிநீர் ஆதாரம்",
    toiletStatus: "கழிப்பறை வசதி",
    chronicDiseases: "நாள்பட்ட நோய்கள்",
    bloodGroup: "இரத்த வகை",
    pregnancyStatus: "கர்ப்ப நிலை",
    vaccinationStatus: "தடுப்பூசி நிலை",
    disabilityStatus: "மாற்றுத்திறனாளி நிலை",
    alertsCount: "அதிக அபாய எச்சரிக்கைகள்",
    maternalStatus: "தாய்வழி சுகாதார நிலை",
    attendanceCheckIn: "GPS வருகை பதிவு",
    checkedIn: "வருகை பதிவு செய்யப்பட்டது",
    checkIn: "செக்-இன்",
    checkOut: "செக்-அவுட்",
    gpsMock: "போலி ஜிபிஎஸ் ஒருங்கிணைப்புகள்",
    signInToPortal: "போர்ட்டலில் உள்நுழையவும்",
    enterCredentials: "சுகாதார அளவீடுகளை அணுக உங்கள் சான்றுகளை உள்ளிடவும்",
    emailAddress: "மின்னஞ்சல் முகவரி",
    passwordLabel: "கடவுச்சொல்",
    keepMeSignedIn: "என்னை உள்நுழைந்தே வைத்திருக்கவும்",
    forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?",
    accessPortal: "போர்ட்டலை அணுகவும்",
    signingIn: "உள்நுழைகிறது...",
    quickDemoAccess: "விரைவான டெமோ அணுகல்",
    liveClinicalMetrics: "நேரடி மருத்துவ நெட்வொர்க் அளவீடுகள்",
    needHelp: "உதவி தேவையா?",
    contactAdmin: "அட்மினை தொடர்பு கொள்ளவும்",
    privacyPolicy: "தனியுரிமைக் கொள்கை",
    hello: "வணக்கம் !",
    pleaseEnterDetails: "தொடர உங்கள் விவரங்களை உள்ளிடவும்"
  },
  mr: {
    title: "जीवन रोशनी",
    subtitle: "सामुदायिक आरोग्य कार्यक्रम",
    offlineMode: "ऑफलाईन मोड",
    online: "ऑनलाईन",
    offline: "ऑफलाईन",
    syncPending: "सिंक प्रलंबित",
    syncSuccess: "केंद्रीय सर्व्हरसह डेटा यशस्वीरित्या सिंक झाला!",
    vhwRole: "ग्राम आरोग्य कार्यकर्ता",
    directorRole: "प्रकल्प संचालक",
    adminRole: "सुपर ॲडमिन (आयतन ट्रस्ट)",
    dashboard: "डॅशबोर्ड",
    villageReg: "गाव नोंदणी",
    familyReg: "कुटुंब नोंदणी",
    individualReg: "वैयक्तिक आरोग्य नोंदणी",
    echr: "इलेक्ट्रॉनिक समुदाय आरोग्य रेकॉर्ड",
    fieldVisits: "क्षेत्र भेट ट्रॅकर",
    communityProg: "सामुदायिक कार्यक्रम",
    hrAttendance: "हजेरी आणि एचआर",
    vulnerableRegistry: "असुरक्षित नोंदणी",
    trainingCenter: "प्रशिक्षण आणि विकास",
    reports: "अहवाल आणि दस्तऐवज",
    riskAlerts: "जोखिम अलर्ट",
    save: "नोंद जतन करा",
    saving: "जतन करत आहे...",
    offlineQueue: "स्थानिक पातळीवर जतन केले (ऑफलाईन)",
    syncNow: "आता सिंक करा",
    name: "नाव",
    age: "वय",
    gender: "लिंग",
    phone: "मोबाईल नंबर",
    village: "गाव",
    selectVillage: "गाव निवडा",
    houseNo: "घर क्रमांक",
    economicStatus: "आर्थिक स्थिती",
    waterSource: "पिण्याच्या पाण्याचा स्रोत",
    toiletStatus: "शौचालय उपलब्धता",
    chronicDiseases: "तीव्र आजार",
    bloodGroup: "रक्त गट",
    pregnancyStatus: "गर्भावस्था स्थिती",
    vaccinationStatus: "लसीकरण स्थिती",
    disabilityStatus: "अपंगत्व स्थिती",
    alertsCount: "उच्च जोखिम अलर्ट",
    maternalStatus: "मातृ आरोग्य स्थिती",
    attendanceCheckIn: "GPS हजेरी चेक-इन",
    checkedIn: "हजेरी नोंदवली",
    checkIn: "चेक-इन",
    checkOut: "चेक-आऊट",
    gpsMock: "सिम्युलेटेड जीपीएस निर्देशक",
    signInToPortal: "पोर्टलमध्ये साइन इन करा",
    enterCredentials: "आरोग्य मेट्रिक्स पाहण्यासाठी तुमचे क्रेडेंशियल प्रविष्ट करा",
    emailAddress: "ईमेल पत्ता",
    passwordLabel: "पासवर्ड",
    keepMeSignedIn: "मला साइन इन ठेवा",
    forgotPassword: "पासवर्ड विसरलात?",
    accessPortal: "पोर्टलवर जा",
    signingIn: "साइन इन होत आहे...",
    quickDemoAccess: "त्वरित डेमो प्रवेश",
    liveClinicalMetrics: "लाइव क्लिनिकल नेटवर्क मेट्रिक्स",
    needHelp: "मदत हवी आहे का?",
    contactAdmin: "अ‍ॅडमिनशी संपर्क साधा",
    privacyPolicy: "गोपनीयता धोरण",
    hello: "नमस्कार !",
    pleaseEnterDetails: "पुढे जाण्यासाठी कृपया आपले तपशील प्रविष्ट करा"
  },
  bn: {
    title: "জীবন রোশনি",
    subtitle: "কমিউনিটি স্বাস্থ্য কর্মসূচি",
    offlineMode: "অফলাইন মোড",
    online: "অনলাইন",
    offline: "অফলাইন",
    syncPending: "সিঙ্ক বাকি আছে",
    syncSuccess: "সেন্ট্রাল সার্ভারের সাথে ডেটা সফলভাবে সিঙ্ক হয়েছে!",
    vhwRole: "গ্রাম্য স্বাস্থ্য কর্মী",
    directorRole: "প্রকল্প পরিচালক",
    adminRole: "সুপার অ্যাডমিন (আয়তন ট্রাস্ট)",
    dashboard: "ড্যাশবোর্ড",
    villageReg: "গ্রাম নিবন্ধন",
    familyReg: "পরিবার নিবন্ধন",
    individualReg: "ব্যক্তিগত স্বাস্থ্য রেজিস্ট্রি",
    echr: "ইলেকট্রনিক স্বাস্থ্য রেকর্ড",
    fieldVisits: "ফিল্ড ভিজিট ট্র্যাকার",
    communityProg: "কমিউনিটি প্রোগ্রাম",
    hrAttendance: "উপস্থিতি ও এইচআর",
    vulnerableRegistry: "অরক্ষিত রেজিস্ট্রি",
    trainingCenter: "প্রশিক্ষণ ও উন্নয়ন",
    reports: "প্রতিবেদন এবং নথি",
    riskAlerts: "ঝুঁকি সতর্কতা",
    save: "সংরক্ষণ করুন",
    saving: "সংরক্ষণ করা হচ্ছে...",
    offlineQueue: "স্থানীয়ভাবে সংরক্ষিত (অফলাইন)",
    syncNow: "এখনই সিঙ্ক করুন",
    name: "নাম",
    age: "বয়স",
    gender: "লিঙ্গ",
    phone: "মোবাইল নম্বর",
    village: "গ্রাম",
    selectVillage: "গ্রাম নির্বাচন করুন",
    houseNo: "বাড়ি নম্বর",
    economicStatus: "অর্থনৈতিক অবস্থা",
    waterSource: "খাবার জলের উৎস",
    toiletStatus: "শৌচাগার প্রাপ্যতা",
    chronicDiseases: "দীর্ঘস্থায়ী রোগ",
    bloodGroup: "রক্তের গ্রুপ",
    pregnancyStatus: "গর্ভাবস্থার অবস্থা",
    vaccinationStatus: "টিকা স্থিতি",
    disabilityStatus: "প্রতিবন্ধী স্থিতি",
    alertsCount: "উচ্চ ঝুঁকি সতর্কতা",
    maternalStatus: "মাতৃস্বাস্থ্য অবস্থা",
    attendanceCheckIn: "জিপিএস উপস্থিতি চেক-ইন",
    checkedIn: "উপস্থিতি নথিভুক্ত",
    checkIn: "চেক-ইন",
    checkOut: "চেক-আউট",
    gpsMock: "সিমুলেটেড জিপিএস স্থানাঙ্ক",
    signInToPortal: "পোর্টেলে সাইন ইন করুন",
    enterCredentials: "স্বাস্থ্য মেট্রিক্স অ্যাক্সেস করতে আপনার শংসাপত্র লিখুন",
    emailAddress: "ইমেল ঠিকানা",
    passwordLabel: "পাসওয়ার্ড",
    keepMeSignedIn: "আমাকে সাইন ইন রাখুন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    accessPortal: "পোর্টাল অ্যাক্সেস করুন",
    signingIn: "সাইন ইন হচ্ছে...",
    quickDemoAccess: "দ্রুত ডেমো অ্যাক্সেस",
    liveClinicalMetrics: "লাইভ ক্লিনিকাল নেটওয়ার্ক মেট্রিক্স",
    needHelp: "সাহায্য প্রয়োজন?",
    contactAdmin: "অ্যাডমিনের সাথে যোগাযোগ করুন",
    privacyPolicy: "গোপনীয়তা নীতি",
    hello: "হ্যালো !",
    pleaseEnterDetails: "চালিয়ে যেতে আপনার বিবরণ লিখুন"
  },
  gu: {
    title: "જીવન રોશની",
    subtitle: "સમુદાય આરોગ્ય કાર્યક્રમ",
    offlineMode: "ઓફલાઇન મોડ",
    online: "ઓનલાઇન",
    offline: "ઓફલાઇન",
    syncPending: "સિંક બાકી છે",
    syncSuccess: "સેન્ટ્રલ સર્વર સાથે ડેટા સફળતાપૂર્વક સિંક થયો છે!",
    vhwRole: "ગ્રામ્ય આરોગ્ય કાર્યકર",
    directorRole: "પ્રોજેક્ટ ડિરેક્ટર",
    adminRole: "સુપર એડમિન (આયતન ટ્રસ્ટ)",
    dashboard: "ડેશબોર્ડ",
    villageReg: "ગામ નોંધણી",
    familyReg: "પરિવાર નોંધણી",
    individualReg: "વ્યક્તિગત આરોગ્ય રજિસ્ટ્રી",
    echr: "ઇલેક્ટ્રોનિક આરોગ્ય રેકોર્ડ",
    fieldVisits: "ફીલ્ડ વિઝિટ ટ્રેકર",
    communityProg: "સામુદાયિક કાર્યક્રમો",
    hrAttendance: "હાજરી અને એચઆર",
    vulnerableRegistry: "અતિ સંવેદનશીલ રજિસ્ટ્રી",
    trainingCenter: "તાલીમ અને વિકાસ",
    reports: "અહેવાલો અને દસ્તાવેજો",
    riskAlerts: "જોખમ ચેતવણીઓ",
    save: "રેકોર્ડ સાચવો",
    saving: "સાચવી રહ્યું છે...",
    offlineQueue: "સ્થાનિક રીતે સાચવેલ (ઓફલાઇન)",
    syncNow: "હમણાં સિંક કરો",
    name: "નામ",
    age: "ઉંમર",
    gender: "લિંગ",
    phone: "મોબાઇલ નંબર",
    village: "ગામ",
    selectVillage: "ગામ પસંદ કરો",
    houseNo: "ઘર નંબર",
    economicStatus: "આર્થિક સ્થિતિ",
    waterSource: "પીવાના પાણીનો સ્રોત",
    toiletStatus: "શૌચાલયની ઉપલબ્ધતા",
    chronicDiseases: "લાંબા ગાળાની બીમારીઓ",
    bloodGroup: "રક્ત જૂથ",
    pregnancyStatus: "ગર્ભાવસ્થાની સ્થિતિ",
    vaccinationStatus: "રસીકરણની સ્થિતિ",
    disabilityStatus: "દિવ્યાંગતાની સ્થિતિ",
    alertsCount: "ઉચ્ચ જોખમ ચેતવણીઓ",
    maternalStatus: "માતૃત્વ આરોગ્ય સ્થિતિ",
    attendanceCheckIn: "GPS હાજરી ચેક-ઇન",
    checkedIn: "હાજરી નોંધાયેલ",
    checkIn: "ચેક-ઇન",
    checkOut: "ચેક-આૌટ",
    gpsMock: "સિમ્યુલેટેડ જીપીએસ કોઓર્ડિનેટ્સ",
    signInToPortal: "પોર્ટલ પર સાઇન ઇન કરો",
    enterCredentials: "આરોગ્ય મેટ્રિક્સ ઍક્સેસ કરવા માટે તમારા ઓળખપત્રો દાખલ કરો",
    emailAddress: "ઇમેઇલ સરનામું",
    passwordLabel: "પાસવર્ડ",
    keepMeSignedIn: "મને સાઇન ઇન રાખો",
    forgotPassword: "પાસવર્ડ ભૂલી ગયા છો?",
    accessPortal: "પોર્ટલ ઍક્સેસ કરો",
    signingIn: "સાઇન ઇન થઈ રહ્યું છે...",
    quickDemoAccess: "ઝડપી ડેમો ઍક્સેસ",
    liveClinicalMetrics: "લાઇવ ક્લિનિકલ નેટવર્ક મેટ્રિક્સ",
    needHelp: "મદદ જોઈએ છે?",
    contactAdmin: "એડમિનનો સંપર્ક કરો",
    privacyPolicy: "ગોપનીયતા નીતિ",
    hello: "નમસ્તે !",
    pleaseEnterDetails: "આગળ વધવા માટે કૃપા કરીને તમારી વિગતો દાખલ કરો"
  }
};

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState('en');

  const t = (key) => {
    return translations[locale][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
