<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // 1. Family Registry
        Schema::create('families', function (Blueprint $table) {
            $table->string('id')->primary(); // Custom ID e.g., FAM-4829-102
            $table->string('village_id');
            $table->foreign('village_id')->references('id')->on('villages')->onDelete('cascade');
            $table->string('house_no');
            $table->text('address')->nullable();
            $table->string('economic_status')->default('BPL'); // BPL, APL, Antyodaya
            $table->string('occupation')->nullable();
            $table->string('drinking_water_source')->default('Tap'); // Tap, Well, Handpump, River
            $table->string('toilet_availability')->default('Yes'); // Yes, No
            $table->string('insurance_details')->nullable();
            $table->string('status')->default('Active'); // Active, Migrated, Inactive
            $table->softDeletes(); // Never permanently delete family records
            $table->timestamps();
        });

        // 2. Individual Health Registry
        Schema::create('individuals', function (Blueprint $table) {
            $table->string('id')->primary(); // Custom ID e.g., JR-4829-01
            $table->string('family_id');
            $table->foreign('family_id')->references('id')->on('families')->onDelete('cascade');
            $table->string('name');
            $table->date('date_of_birth')->nullable(); // Use DOB instead of age for accuracy
            $table->integer('age'); // Kept for quick lookup / legacy
            $table->string('gender'); // Male, Female, Other
            $table->string('mobile_number')->nullable();
            $table->string('aadhaar_masked')->nullable();
            $table->string('blood_group')->nullable();
            $table->string('pregnancy_status')->default('No'); // Yes, No
            $table->string('vaccination_status')->default('None'); // Full, Partial, None
            $table->string('disability_status')->default('No'); // Yes, No
            $table->text('allergy_history')->nullable();
            $table->string('malnutrition_status')->default('none'); // none, moderate, severe
            $table->string('living_alone')->default('no'); // yes, no
            $table->string('status')->default('Active'); // Active, Migrated, Deceased
            $table->softDeletes(); // Never permanently delete individual records
            $table->timestamps();
        });

        // 3. Electronic Community Health Records (ECHR) — Vitals Snapshot
        // NOTE: Full clinical data is split into separate ECHR tables (migration 000006)
        // This table stores the latest baseline vitals only.
        Schema::create('health_records', function (Blueprint $table) {
            $table->id();
            $table->string('individual_id');
            $table->foreign('individual_id')->references('id')->on('individuals')->onDelete('cascade');
            $table->decimal('height_cm', 5, 2)->nullable();
            $table->decimal('weight_kg', 5, 2)->nullable();
            $table->integer('bp_systolic')->nullable();
            $table->integer('bp_diastolic')->nullable();
            $table->integer('blood_sugar_mgdl')->nullable();
            $table->decimal('temperature_f', 4, 1)->nullable();
            $table->integer('pulse_rate')->nullable();
            $table->integer('spo2_percent')->nullable(); // Oxygen saturation
            $table->json('chronic_diseases')->nullable(); // e.g. ["Hypertension", "Diabetes"]
            $table->text('general_notes')->nullable();
            $table->date('recorded_on');
            $table->foreignId('recorded_by')->constrained('users');
            $table->softDeletes(); // Never permanently delete health records
            $table->timestamps();
        });

        // 4. Clinical Risk Alerts (Rule-based — auto-generated by RiskAlertService)
        Schema::create('risk_alerts', function (Blueprint $table) {
            $table->id();
            $table->string('individual_id');
            $table->foreign('individual_id')->references('id')->on('individuals')->onDelete('cascade');
            $table->string('type'); // Hypertension, SAM, High-Risk-Pregnancy, Missed-Followup, etc.
            $table->string('severity'); // low, medium, high, critical
            $table->text('reason'); // Auto-generated rule description
            $table->json('trigger_data')->nullable(); // Raw values that triggered the alert e.g. {"bp_systolic": 165}
            $table->string('status')->default('Active'); // Active, Acknowledged, Resolved
            $table->foreignId('acknowledged_by')->nullable()->constrained('users')->onDelete('set null');
            $table->timestamp('acknowledged_at')->nullable();
            $table->timestamp('resolved_at')->nullable();
            $table->foreignId('resolved_by')->nullable()->constrained('users')->onDelete('set null');
            $table->softDeletes();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('risk_alerts');
        Schema::dropIfExists('health_records');
        Schema::dropIfExists('individuals');
        Schema::dropIfExists('families');
    }
};
